"""Timezone and cron schedule calculation and GitHub Actions workflow generator."""
import os
import re
from datetime import datetime, time
from typing import List, Tuple, Dict, Any, Optional, Union
import pytz


DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
DAY_MAP = {
    "sun": 0, "sunday": 0, "0": 0,
    "mon": 1, "monday": 1, "1": 1,
    "tue": 2, "tuesday": 2, "2": 2,
    "wed": 3, "wednesday": 3, "3": 3,
    "thu": 4, "thursday": 4, "4": 4,
    "fri": 5, "friday": 5, "5": 5,
    "sat": 6, "saturday": 6, "6": 6,
}


def local_to_utc_cron(
    days: List[Union[str, int]],
    local_time_str: str,
    tz_name: str = "Asia/Kolkata"
) -> Tuple[str, Dict[str, Any]]:
    """Convert local days and time into a UTC cron expression for GitHub Actions.
    
    Args:
        days: List of day names or numbers (e.g., ['Monday', 'Wednesday', 'Friday'] or [1, 3, 5])
        local_time_str: Time string in "HH:MM" (24h) or "HH:MM AM/PM"
        tz_name: IANA timezone name (e.g., "Asia/Kolkata", "America/New_York")
        
    Returns:
        Tuple of (cron_expression_str, details_dict)
    """
    # Parse time
    clean_time = local_time_str.strip().upper()
    if "AM" in clean_time or "PM" in clean_time:
        parsed_time = datetime.strptime(clean_time, "%I:%M %p").time()
    else:
        parsed_time = datetime.strptime(clean_time, "%H:%M").time()

    tz = pytz.timezone(tz_name)
    # Reference date (e.g. Sunday 2026-01-04 to easily track weekday shifts)
    # 2026-01-04 was a Sunday
    sunday_base = datetime(2026, 1, 4, parsed_time.hour, parsed_time.minute, 0)

    # Normalize day indices (0=Sun, 1=Mon, ..., 6=Sat)
    normalized_days = set()
    for d in days:
        key = str(d).strip().lower()
        if key in DAY_MAP:
            normalized_days.add(DAY_MAP[key])
        else:
            raise ValueError(f"Unknown day: {d}")

    if not normalized_days:
        raise ValueError("At least one day must be selected.")

    utc_minute = 0
    utc_hour = 0
    utc_days = set()

    for local_day_idx in sorted(normalized_days):
        # Calculate localized date for this weekday
        day_date = sunday_base.replace(day=sunday_base.day + local_day_idx)
        localized_dt = tz.localize(day_date)
        utc_dt = localized_dt.astimezone(pytz.UTC)

        utc_minute = utc_dt.minute
        utc_hour = utc_dt.hour
        # In Python datetime, weekday(): 0=Mon, 6=Sun. Convert to 0=Sun, 1=Mon..
        py_weekday = utc_dt.weekday()
        cron_weekday = (py_weekday + 1) % 7
        utc_days.add(cron_weekday)

    cron_days_str = ",".join(str(d) for d in sorted(utc_days))
    cron_expr = f"{utc_minute} {utc_hour} * * {cron_days_str}"

    details = {
        "local_time": local_time_str,
        "local_days": [DAY_NAMES[d] for d in sorted(normalized_days)],
        "timezone": tz_name,
        "utc_time": f"{utc_hour:02d}:{utc_minute:02d} UTC",
        "utc_cron": cron_expr,
    }

    return cron_expr, details


def generate_workflow_yaml(cron_expr: str) -> str:
    """Generate GitHub Actions workflow content with given cron expression."""
    return f"""name: Autonomous Google Form Submission

on:
  schedule:
    # Auto-generated by Auto Google Form Filler
    - cron: '{cron_expr}'
  workflow_dispatch:
    # Allows manual test triggers anytime from GitHub Web / Mobile App

jobs:
  fill-form:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Autonomous Form Filler
        env:
          SMTP_HOST: ${{{{ secrets.SMTP_HOST }}}}
          SMTP_PORT: ${{{{ secrets.SMTP_PORT }}}}
          SMTP_USER: ${{{{ secrets.SMTP_USER }}}}
          SMTP_PASSWORD: ${{{{ secrets.SMTP_PASSWORD }}}}
          ALERT_RECIPIENT_EMAIL: ${{{{ secrets.ALERT_RECIPIENT_EMAIL }}}}
          FORM_SUBMISSION_EMAIL: ${{{{ secrets.FORM_SUBMISSION_EMAIL }}}}
        run: |
          python src/main.py
"""


def save_workflow_file(cron_expr: str, repo_root: str = ".") -> str:
    """Save the GitHub Actions workflow file to .github/workflows/scheduled_submission.yml."""
    workflows_dir = os.path.join(repo_root, ".github", "workflows")
    os.makedirs(workflows_dir, exist_ok=True)
    file_path = os.path.join(workflows_dir, "scheduled_submission.yml")

    content = generate_workflow_yaml(cron_expr)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    return file_path


if __name__ == "__main__":
    import sys
    print("=== Timezone & Schedule Generator ===")
    tz = input("Enter timezone [Default: Asia/Kolkata]: ").strip() or "Asia/Kolkata"
    days_input = input("Enter days separated by comma (e.g. Mon,Wed,Fri) [Default: Mon,Wed,Fri]: ").strip() or "Mon,Wed,Fri"
    time_input = input("Enter local time (e.g. 09:30 or 09:30 AM) [Default: 09:30]: ").strip() or "09:30"

    days_list = [d.strip() for d in days_input.split(",") if d.strip()]
    cron, info = local_to_utc_cron(days_list, time_input, tz_name=tz)

    print("\n--- Converted Schedule ---")
    print(f"Local Time: {info['local_time']} ({', '.join(info['local_days'])}) in {info['timezone']}")
    print(f"UTC Equivalent: {info['utc_time']}")
    print(f"Generated Cron: {cron}")

    update = input("\nWrite to .github/workflows/scheduled_submission.yml? (y/n) [Default: y]: ").strip().lower()
    if update != "n":
        saved = save_workflow_file(cron)
        print(f"✅ Saved workflow to: {saved}")
